default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  url: postgres://nhrqeplwpmajzb:5b736e7bbd70e2a6f61f00925955c3da9c0be6a65328a933b5dc6d12ae64823b@ec2-34-231-56-78.compute-1.amazonaws.com:5432/dcrijnjptmlemb 

test:
  <<: *default
  database: alunos_comunidade_test

production:
  <<: *default
  database: alunos_comunidade_production
  username: alunos_comunidade
  password: <%= ENV['ALUNOS_COMUNIDADE_DATABASE_PASSWORD'] %>
